security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        login:
            pattern: ^/api/user/login
            stateless: true

        public:
            pattern: ^/api/(games|course|reviews|community-game|review)
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/user/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/games, roles: PUBLIC_ACCESS }
        - { path: ^/api/course, roles: PUBLIC_ACCESS }
        - { path: ^/api/review, roles: PUBLIC_ACCESS }
        - { path: ^/api/community-game, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }